name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sectioncritical/avr-build
      credentials:
        username: kroesche
        password: ${{ secrets.CONTAINER_ACCESS }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean
        run: make -C build clean
      - name: build
        run: make -C build VERSION=${GITHUB_REF#refs/tags/}
      - name: check
        run: make -C build check
      - name: package
        run: make -C build package VERSION=${GITHUB_REF#refs/tags/v}
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/canboot-*.tar.gz

# tools for releases
# python git-changelog to generate changelog
# python-semantic-release
# python package named conventional
#
# ncipollo/release-action
